name: Update DOSDP pattern files
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/patterns/*'
jobs:
  dosdp:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.3.1
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: Refreshing DOSDP patterns files
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' GITHUB_ACTION=true IMP=false MIR=false ../patterns/definitions.owl
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Refreshing DOSDP patterns files
          title: 'Update DOSDP pattern files'
          body: |
            Updates all DOSDP generated files.
          assignees: matentzn